name: Setup Gitlab Access
description: Setup Gitlab Access

inputs:
  gitlab-access-token:
    description: The Gitlab Access Token secret
    required: true

runs:
  using: composite
  steps:

    - name: Setup Gitlab Access
      shell: bash
      run: |
        git config --global url."https://api:${{ inputs.gitlab-access-token }}@gitlab.com/".insteadOf "https://gitlab.com/"
        git config --global url."https://ssh:${{ inputs.gitlab-access-token }}@gitlab.com/".insteadOf "ssh://git@gitlab.com/"
        git config --global url."https://git:${{ inputs.gitlab-access-token }}@gitlab.com/".insteadOf "git@gitlab.com:"
