name: Setup Gradle
description: Setup Gradle

runs:
  using: composite
  steps:

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Make Gradle wrapper executable
      shell: bash
      run: chmod +x ./gradlew
