name: Build

on:
  push:
    branches :
      - '**'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
    with:
      isRelease: false
    secrets: inherit
